apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: els-ai
resources:
  - namespace.yaml
  - config.yaml
  - secrets.yaml
  - postgres.yaml
  - media-assets-pvc.yaml
  - auth-service.yaml
  - quiz-service.yaml
  - media-service.yaml
  - ai-service.yaml
  - gateway.yaml
  - frontend.yaml
  - ingress.yaml
