apiVersion: v1
kind: Secret
metadata:
  name: els-ai-secrets
  namespace: els-ai
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "change-me"
  JWT_SECRET: "change-me"
  ABLY_API_KEY: "change-me"
  AWS_ACCESS_KEY_ID: "change-me"
  AWS_SECRET_ACCESS_KEY: "change-me"
  S3_BUCKET_NAME: "change-me"
