import { StyleSheet } from 'react-native';

export const qFormS = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F5F7FF' },
  header: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingBottom: 12, backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#F0F0F8' },
  backBtn: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  backArrow: { fontSize: 28, color: '#1a1a2e', fontWeight: '300', lineHeight: 34 },
  titleText: { fontSize: 17, fontWeight: '900', color: '#1a1a2e' },
  subTitle: { fontSize: 11, color: '#9A9AB0', fontWeight: '600', marginTop: 2 },
  saveBtn: { backgroundColor: '#4A90E2', borderRadius: 10, paddingHorizontal: 18, paddingVertical: 8 },
  saveBtnDisabled: { opacity: 0.5 },
  saveBtnText: { color: '#fff', fontWeight: '800', fontSize: 13 },

  tabBar: { flexDirection: 'row', backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#F0F0F8' },
  tab: { flex: 1, paddingVertical: 12, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabActive: { borderBottomColor: '#4A90E2' },
  tabText: { fontSize: 13, fontWeight: '600', color: '#9A9AB0' },
  tabTextActive: { color: '#4A90E2', fontWeight: '800' },

  toast: { marginHorizontal: 16, marginTop: 8, borderRadius: 10, padding: 10, borderWidth: 1, borderColor: '#E0E4F0', backgroundColor: '#F0F4FF' },
  toastText: { fontSize: 13, fontWeight: '600', color: '#1a1a2e', textAlign: 'center' },
  toastError: { backgroundColor: '#FFE8E8', borderColor: '#FF7043' },
  toastErrorText: { color: '#B91C1C' },
  toastSuccess: { backgroundColor: '#D6F5D6', borderColor: '#7DC67A' },
  toastSuccessText: { color: '#1A6B1A' },

  tabContent: { padding: 16, gap: 16, paddingBottom: 40 },
  group: { gap: 8 },
  groupLabel: { fontSize: 10, fontWeight: '800', color: '#9A9AB0', letterSpacing: 1, textTransform: 'uppercase', paddingLeft: 4 },
  fieldCard: { backgroundColor: '#fff', borderRadius: 16, padding: 14, gap: 10, shadowColor: '#1a1a2e', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 4, elevation: 1 },
  fieldLabel: { fontSize: 11, fontWeight: '700', color: '#9A9AB0', textTransform: 'uppercase', letterSpacing: 0.5 },
  input: { fontSize: 14, color: '#1a1a2e', fontWeight: '500', paddingVertical: 6 },
  divider: { height: 1, backgroundColor: '#F0F0F8' },
  selectorRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 6 },
  selectorVal: { fontSize: 14, color: '#1a1a2e', fontWeight: '500' },
  selectorPlaceholder: { fontSize: 14, color: '#B0B8D0' },
  twoCol: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' },
  colDivider: { width: 1, backgroundColor: '#F0F0F8', alignSelf: 'stretch', marginVertical: 4 },

  qtypeChip: { flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: '#F0F0F8', borderWidth: 1.5, borderColor: 'transparent' },
  qtypeEmoji: { fontSize: 16 },
  qtypeLabel: { fontSize: 12, fontWeight: '600', color: '#9A9AB0' },
  qtypeDesc: { fontSize: 12, color: '#9A9AB0', fontStyle: 'italic', lineHeight: 18, paddingTop: 4 },

  uploadBtn: { borderRadius: 8, borderWidth: 1, borderColor: '#D6EAFF', backgroundColor: '#F5F9FF', paddingVertical: 10, alignItems: 'center' },
  uploadBtnText: { fontSize: 13, fontWeight: '700', color: '#4A90E2' },
  mediaRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 8 },
  mediaThumb: { width: 56, height: 44, borderRadius: 8, backgroundColor: '#F0F0F8' },
  mediaName: { fontSize: 12, color: '#9A9AB0', fontWeight: '500' },
  audioIcon: { fontSize: 22 },
  playBtn: { borderRadius: 8, backgroundColor: '#D6EAFF', paddingHorizontal: 10, paddingVertical: 6 },
  playBtnText: { fontSize: 12, fontWeight: '700', color: '#1A4DA2' },
  removeBtn: { width: 28, height: 28, borderRadius: 8, backgroundColor: '#FFE8E8', alignItems: 'center', justifyContent: 'center' },
  removeBtnWide: { borderRadius: 8, backgroundColor: '#FFE8E8', paddingHorizontal: 10, paddingVertical: 6 },
  removeBtnText: { fontSize: 11, fontWeight: '800', color: '#FF7043' },

  secGroup: { backgroundColor: '#fff', borderRadius: 16, overflow: 'hidden' },
  secHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#F0F0F8' },
  secTitle: { fontSize: 14, fontWeight: '800', color: '#1a1a2e' },
  secHint: { fontSize: 12, color: '#9A9AB0', paddingHorizontal: 14, paddingVertical: 8 },
  addBtn: { backgroundColor: '#D6EAFF', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 5 },
  addBtnText: { fontSize: 12, fontWeight: '800', color: '#1A4DA2' },

  optBlock: { borderBottomWidth: 1, borderBottomColor: '#F5F7FF' },
  optBlockHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 10, paddingVertical: 10 },
  optNumBadge: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#E0E4F0', alignItems: 'center', justifyContent: 'center' },
  optNum: { fontSize: 12, fontWeight: '800', color: '#9A9AB0' },
  optInput: { fontSize: 14, color: '#1a1a2e', fontWeight: '500', backgroundColor: '#F8F9FF', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: '#ECEEF4' },
  correctBtn: { width: 32, height: 32, borderRadius: 8, backgroundColor: '#F0F0F8', alignItems: 'center', justifyContent: 'center' },
  correctBtnActive: { backgroundColor: '#D6F5D6' },
  correctBtnText: { fontSize: 15, color: '#9A9AB0', fontWeight: '700' },
  correctBtnTextActive: { color: '#7DC67A' },
  pairHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F5F7FF' },
  pairNum: { fontSize: 13, fontWeight: '800', color: '#1a1a2e' },
  gridChip: { borderRadius: 14, borderWidth: 1.5, borderColor: '#E0E0EE', backgroundColor: '#F8F9FC', paddingHorizontal: 18, paddingVertical: 10, alignItems: 'center', minWidth: 72 },
  gridChipActive: { backgroundColor: '#7B4FCA', borderColor: '#7B4FCA' },
  gridChipText: { fontSize: 15, fontWeight: '900', color: '#1a1a2e' },
  gridChipTextActive: { color: '#fff' },
  gridChipSub: { fontSize: 9, fontWeight: '700', color: '#9A9AB0', marginTop: 2 },
  removeBtnSmallText: { fontSize: 12, fontWeight: '800', color: '#FF7043' },
  logicoWorksheetPreview: { width: '100%', height: 180, borderRadius: 10, backgroundColor: '#F8FAFC', marginBottom: 10 },
  logicoBlockerBanner: { backgroundColor: '#FEE2E2', borderWidth: 1, borderColor: '#FCA5A5', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8, marginBottom: 10 },
  logicoBlockerText: { fontSize: 12, fontWeight: '700', color: '#B91C1C' },
  logicoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  logicoCard: { width: '48%', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, padding: 10, gap: 8, backgroundColor: '#FFFFFF' },
  logicoButtonCell: { gap: 8, alignItems: 'center', justifyContent: 'center' },
  logicoButtonLabel: { fontSize: 12, fontWeight: '700', color: '#334155', textAlign: 'center' },
  logicoSlotCell: { gap: 4 },
  logicoSlotInput: { fontSize: 14, color: '#1a1a2e', fontWeight: '700', backgroundColor: '#F8F9FF', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: '#ECEEF4', textAlign: 'center' },
  logicoLabelCell: { flex: 1, gap: 4 },
  logicoButtonCircle: { borderWidth: 2, borderColor: '#1f2937', alignItems: 'center', justifyContent: 'center' },
  logicoButtonRingInner: { backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#9ca3af' },
  logicoPreviewWrap: { marginHorizontal: 14, marginBottom: 14, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, overflow: 'hidden' },
  logicoPreviewRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 10, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  logicoPreviewSlotText: { width: 24, fontSize: 12, fontWeight: '800', color: '#334155', textAlign: 'center' },
  logicoPreviewOptionText: { flex: 1, fontSize: 12, fontWeight: '600', color: '#1e293b' },
  logicoPreviewEmptyButton: { width: 26, height: 26, borderRadius: 13, backgroundColor: '#E2E8F0', borderWidth: 1, borderColor: '#CBD5E1' },

  previewCard: { backgroundColor: '#fff', borderRadius: 20, overflow: 'hidden' },
  previewHero: { flexDirection: 'row', alignItems: 'flex-start', gap: 14, padding: 20 },
  previewTypeBadge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 3, alignSelf: 'flex-start', marginBottom: 6 },
  previewTypeBadgeText: { fontSize: 11, fontWeight: '700' },
  previewTitle: { fontSize: 17, fontWeight: '900', color: '#1a1a2e', lineHeight: 24 },
  previewMeta: { fontSize: 12, color: '#9A9AB0', marginTop: 4 },
  previewStats: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#F5F7FF' },
  previewStat: { flex: 1, alignItems: 'center', paddingVertical: 14, borderRightWidth: 1, borderRightColor: '#F5F7FF', gap: 2 },
  previewStatVal: { fontSize: 20, fontWeight: '900', color: '#1a1a2e' },
  previewStatLabel: { fontSize: 10, fontWeight: '700', color: '#9A9AB0', textTransform: 'uppercase' },
  previewInstBlock: { margin: 14, backgroundColor: '#F8F9FF', borderRadius: 12, padding: 12 },
  previewInstText: { fontSize: 13, color: '#5A6A8A', lineHeight: 20 },
  previewImage: { width: '100%', height: 180, marginBottom: 8 },
  previewOptRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F5F7FF', borderRadius: 0 },
  previewOptDot: { width: 26, height: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  previewOptText: { flex: 1, fontSize: 14, fontWeight: '600', color: '#1a1a2e' },
  previewCorrectBadge: { fontSize: 14, color: '#7DC67A', fontWeight: '800' },
  previewPairRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#F5F7FF', justifyContent: 'space-between' },
  previewPairText: { fontSize: 13, fontWeight: '700', color: '#1a1a2e', flex: 1, textAlign: 'center' },
});

export const fbS = StyleSheet.create({
  previewBox: { backgroundColor: '#F0F7FF', borderRadius: 14, padding: 16, borderWidth: 1, borderColor: '#C5D8F8' },
  previewLabel: { fontSize: 9, fontWeight: '800', color: '#4A90E2', letterSpacing: 1, marginBottom: 8, textTransform: 'uppercase' },
  previewSentence: { fontSize: 17, fontWeight: '600', color: '#1a1a2e', lineHeight: 26, textAlign: 'center' },
  previewBlank: { fontWeight: '900', borderBottomWidth: 2, paddingHorizontal: 4 },
  section: { backgroundColor: '#fff', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#EEF0F8' },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  sectionIcon: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  sectionTitle: { fontSize: 14, fontWeight: '800', color: '#1a1a2e' },
  sectionHint: { fontSize: 11, color: '#9A9AB0', marginTop: 2 },
  optional: { fontWeight: '500', color: '#B0B8D0' },
  textArea: { borderWidth: 1.5, borderColor: '#E0E8F5', borderRadius: 12, padding: 12, fontSize: 14, color: '#1a1a2e', minHeight: 72, backgroundColor: '#FAFBFF' },
  textInput: { borderWidth: 1.5, borderColor: '#E0E8F5', borderRadius: 12, padding: 12, fontSize: 14, color: '#1a1a2e', backgroundColor: '#FAFBFF' },
  emptyOptions: { alignItems: 'center', paddingVertical: 24, marginHorizontal: 14, marginBottom: 12, borderWidth: 1.5, borderColor: '#E0E8F5', borderStyle: 'dashed', borderRadius: 12, backgroundColor: '#FAFBFF' },
  emptyOptionsTxt: { fontSize: 13, color: '#9A9AB0', fontWeight: '600' },
});

export const mmS = StyleSheet.create({
  section: { backgroundColor: '#fff', borderRadius: 18, padding: 16, shadowColor: '#7B4FCA', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.07, shadowRadius: 10, elevation: 3 },
  sectionTitle: { fontSize: 14, fontWeight: '800', color: '#1a1a2e', marginBottom: 3 },
  sectionHint: { fontSize: 12, color: '#9A9AB0', fontWeight: '500', marginBottom: 12 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14 },
  gridRow: { flexDirection: 'row', gap: 10 },
  gridChip: { borderRadius: 14, borderWidth: 1.5, borderColor: '#DDD8F0', backgroundColor: '#FAFBFF', paddingVertical: 14, alignItems: 'center', gap: 3 },
  gridChipSel: { borderRadius: 14, paddingVertical: 14, alignItems: 'center', gap: 3 },
  gridChipMain: { fontSize: 17, fontWeight: '900', color: '#1a1a2e' },
  gridChipMainSel: { fontSize: 17, fontWeight: '900', color: '#fff' },
  gridChipSub: { fontSize: 10, fontWeight: '700', color: '#9A9AB0' },
  gridChipSubSel: { fontSize: 10, fontWeight: '700', color: 'rgba(255,255,255,0.75)' },
  randomBtn: { borderRadius: 11, paddingHorizontal: 14, paddingVertical: 9 },
  randomBtnText: { fontSize: 12, fontWeight: '800', color: '#fff' },
  unlimitedChip: { borderRadius: 10, borderWidth: 1.5, borderColor: '#DDD8F0', backgroundColor: '#FAFBFF', paddingVertical: 8, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  unlimitedChipSel: { borderRadius: 10, paddingVertical: 8, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  unlimitedChipText: { fontSize: 13, fontWeight: '800', color: '#1a1a2e' },
  unlimitedChipTextSel: { fontSize: 13, fontWeight: '800', color: '#fff' },
  unlimitedChipSub: { fontSize: 10, fontWeight: '600', color: '#9A9AB0' },
  unlimitedChipSubSel: { fontSize: 10, fontWeight: '600', color: 'rgba(255,255,255,0.75)' },
  clickGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  clickChip: { borderRadius: 10, borderWidth: 1.5, borderColor: '#DDD8F0', backgroundColor: '#FAFBFF', paddingVertical: 8, alignItems: 'center', gap: 1 },
  clickChipSel: { borderRadius: 10, paddingVertical: 8, alignItems: 'center', gap: 1 },
  clickChipNum: { fontSize: 17, fontWeight: '900', color: '#1a1a2e' },
  clickChipNumSel: { fontSize: 17, fontWeight: '900', color: '#fff' },
  clickChipSub: { fontSize: 9, fontWeight: '700', color: '#9A9AB0' },
  clickChipSubSel: { fontSize: 9, fontWeight: '700', color: 'rgba(255,255,255,0.8)' },
  pairCard: { backgroundColor: '#F8F9FF', borderRadius: 12, borderWidth: 1.5, borderColor: '#E2E8FF', alignItems: 'center', justifyContent: 'center', paddingVertical: 10, paddingHorizontal: 4, gap: 5 },
  pairCardEmpty: { borderStyle: 'dashed', borderColor: '#C8D0EE', backgroundColor: '#FAFBFF' },
  pairImgPlaceholder: { backgroundColor: '#EEF0FA', alignItems: 'center', justifyContent: 'center' },
  pairImgPlaceholderText: { fontSize: 22, color: '#C0C8E0', fontWeight: '300' },
  pairLabel: { fontSize: 10, fontWeight: '700', color: '#1a1a2e', textAlign: 'center', paddingHorizontal: 2 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(15,10,40,0.55)', justifyContent: 'flex-end' },
  modalSheet: { backgroundColor: '#fff', borderTopLeftRadius: 26, borderTopRightRadius: 26, maxHeight: '85%' },
  modalHeaderGrad: { borderTopLeftRadius: 26, borderTopRightRadius: 26, paddingHorizontal: 20, paddingVertical: 16 },
  modalHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  modalTitle: { fontSize: 16, fontWeight: '900', color: '#1a1a2e' },
  modalHint: { fontSize: 12, color: '#7B60B0', fontWeight: '500', marginTop: 2 },
  modalClose: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.7)', alignItems: 'center', justifyContent: 'center' },
  modalCloseText: { fontSize: 13, fontWeight: '800', color: '#6A7280' },
  assetCell: { alignItems: 'center', backgroundColor: '#F8F9FF', borderRadius: 12, borderWidth: 1.5, borderColor: '#E2E8FF', padding: 8, gap: 5, overflow: 'hidden' },
  assetCellCurrent: { borderColor: '#7B4FCA', backgroundColor: '#EDE4FF', borderWidth: 2 },
  assetCellUsed: { opacity: 0.32 },
  assetLabel: { fontSize: 10, fontWeight: '700', color: '#1a1a2e', textAlign: 'center' },
  assetCurrentRing: { position: 'absolute', top: 0, left: 0, right: 0, height: 3, borderTopLeftRadius: 10, borderTopRightRadius: 10 },
});
