apiVersion: apps/v1
kind: Deployment
metadata:
  name: achievement-service
  namespace: els-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: achievement-service
  template:
    metadata:
      labels:
        app: achievement-service
    spec:
      containers:
        - name: achievement-service
          image: harishdell/els-ai-achievement-service:a4f348f311ca3c0c3d06c97eebc01333a78f84d3
          imagePullPolicy: Always
          ports:
            - containerPort: 4007
          env:
            - name: PORT
              value: "4007"
          envFrom:
            - configMapRef:
                name: els-ai-config
            - secretRef:
                name: els-ai-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 4007
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 4007
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: achievement-service
  namespace: els-ai
spec:
  selector:
    app: achievement-service
  ports:
    - name: http
      port: 4007
      targetPort: 4007
