apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-service
  namespace: els-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classroom-service
  template:
    metadata:
      labels:
        app: classroom-service
    spec:
      containers:
        - name: classroom-service
          image: harishdell/els-ai-classroom-service:9f9ed58dda4da95aea70a92f615c20292b587b61
          imagePullPolicy: Always
          ports:
            - containerPort: 4006
          env:
            - name: PORT
              value: "4006"
          envFrom:
            - configMapRef:
                name: els-ai-config
            - secretRef:
                name: els-ai-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 4006
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 4006
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: classroom-service
  namespace: els-ai
spec:
  selector:
    app: classroom-service
  ports:
    - name: http
      port: 4006
      targetPort: 4006
