apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: els-ai
resources:
  - namespace.yaml
  - config.yaml
  - secrets.yaml
  - media-assets-pv.yaml
  - media-assets-pvc.yaml
  - core-api.yaml
  - workers.yaml
  - migrations-job.yaml
  - media-service.yaml
  - ai-service.yaml
  - gateway.yaml
  - frontend.yaml
  - ingress.yaml
