apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: els-ai
resources:
  - namespace.yaml
  - config.yaml
  - media-assets-pv.yaml
  - media-assets-pvc.yaml
  - auth-service.yaml
  - quiz-service.yaml
  - media-service.yaml
  - ai-service.yaml
  - gateway.yaml
  - classroom-service.yaml
  - achievement-service.yaml
  - question-bank-service.yaml
  - content-service.yaml
  - topic-service.yaml
  - assignment-service.yaml
  - org-service.yaml
  - notification-service.yaml
  - story-service.yaml
  - frontend.yaml
  - ingress.yaml
  
images:
  - name: harishdell/els-ai-achievement-service
  - name: harishdell/els-ai-ai-service
  - name: harishdell/els-ai-assignment-service
  - name: harishdell/els-ai-auth-service
  - name: harishdell/els-ai-classroom-service
  - name: harishdell/els-ai-content-service
  - name: harishdell/els-ai-frontend
  - name: harishdell/els-ai-gateway
  - name: harishdell/els-ai-media-service
  - name: harishdell/els-ai-notification-service
  - name: harishdell/els-ai-org-service
  - name: harishdell/els-ai-question-bank-service
  - name: harishdell/els-ai-quiz-service
  - name: harishdell/els-ai-story-service
  - name: harishdell/els-ai-topic-service