apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-assets-pvc
  namespace: els-ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
