apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: els-ai
spec:
  replicas: 1
  selector:
    matchLabels:      
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: harishdell/els-ai-notification-service:9f9ed58dda4da95aea70a92f615c20292b587b61
          imagePullPolicy: Always
          ports:
            - containerPort: 4013
          env:
            - name: PORT
              value: "4013"
          envFrom:
            - configMapRef:
                name: els-ai-config
            - secretRef:
                name: els-ai-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 4013
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 4013
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: els-ai
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: 4013
      targetPort: 4013
