import { StyleSheet } from 'react-native';

export const FRAME_BUTTON_SIZE = 46;
export const FRAME_SLOT_COUNT = 10;

export const logicopiccoloStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#253729',
  },
  content: {
    flex: 1,
    padding: 10,
    gap: 12,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#e6f7ea',
  },
  subtitle: {
    fontSize: 13,
    color: '#c1ddc8',
  },
  headerBar: {
    height: 54,
    backgroundColor: '#1f1f22',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3a3a3a',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerBtn: {
    minWidth: 86,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 16,
    backgroundColor: '#2b2b2f',
    alignItems: 'center',
  },
  headerBtnText: {
    fontSize: 12,
    fontWeight: '800',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#f5f5f5',
    fontSize: 16,
    fontWeight: '800',
    marginHorizontal: 8,
  },
  frameHost: {
    flex: 1,
    minHeight: 520,
  },
  frameContainer: {
    borderWidth: 6,
    borderColor: '#14361E',
    borderRadius: 18,
    backgroundColor: '#1E4D2B',
    padding: 8,
    shadowColor: '#0f172a',
    shadowOpacity: 0.14,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  frameInner: {
    position: 'relative',
    borderRadius: 12,
    borderWidth: 2.5,
    borderColor: '#294f35',
    backgroundColor: '#23452f',
    overflow: 'hidden',
  },
  topBar: {
    height: 54,
    paddingHorizontal: 12,
    backgroundColor: '#1f1f22',
    borderBottomWidth: 1.5,
    borderColor: '#3a3a3a',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topBarTitle: {
    fontSize: 15,
    color: '#f5f5f5',
    fontWeight: '800',
  },
  flipButton: {
    backgroundColor: '#3a924a',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
  },
  flipButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  boardRow: {
    flexDirection: 'row',
    minHeight: 260,
    borderBottomWidth: 1.5,
    borderColor: '#2d6b3c',
  },
  webViewWrap: {
    flex: 1,
    borderRightWidth: 1.5,
    borderColor: '#2d6b3c',
    backgroundColor: '#ffffff',
  },
  webView: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  webIframeWrap: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  rightRail: {
    width: 78,
    borderLeftWidth: 1.5,
    borderColor: '#2d6b3c',
    backgroundColor: '#173523',
  },
  tray: {
    height: 84,
    backgroundColor: '#1C3E29',
    borderTopWidth: 1.5,
    borderColor: '#2d6b3c',
  },
  floatingLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  buttonCircle: {
    width: FRAME_BUTTON_SIZE,
    height: FRAME_BUTTON_SIZE,
    borderRadius: FRAME_BUTTON_SIZE / 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
    shadowColor: '#0f172a',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  buttonLabel: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  slotColumn: {
    width: 78,
    backgroundColor: '#173523',
  },
  slotRow: {
    flex: 1,
    borderBottomWidth: 1,
    borderColor: '#4b2a6b',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  slotRowLast: {
    borderBottomWidth: 0,
  },
  slot: {
    width: FRAME_BUTTON_SIZE + 8,
    height: FRAME_BUTTON_SIZE + 8,
    borderRadius: 18,
    borderWidth: 2.5,
    borderColor: '#3f3f3f',
    backgroundColor: '#2a2a2a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  slotActive: {
    borderColor: '#68d391',
    backgroundColor: '#3d3d3d',
  },
  slotOccupiedText: {
    fontSize: 10,
    color: '#d1d5db',
    fontWeight: '700',
  },
  selectorWrap: {
    gap: 8,
  },
  selectorTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1e293b',
  },
  selectorRow: {
    flexDirection: 'row',
    gap: 8,
    paddingBottom: 2,
  },
  thumb: {
    width: 130,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    padding: 10,
    gap: 6,
  },
  thumbSelected: {
    borderColor: '#2f9e44',
    backgroundColor: '#f0fdf4',
  },
  thumbBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  thumbTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0f172a',
  },
  previewPanel: {
    marginTop: 2,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 10,
  },
  cardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
    marginBottom: 10,
  },
  cardTile: {
    minWidth: 140,
    maxWidth: 180,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  cardTileImage: {
    width: '100%',
    aspectRatio: 0.72,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    marginBottom: 8,
    backgroundColor: '#e2e8f0',
  },
  cardTilePlaceholder: {
    width: '100%',
    aspectRatio: 0.72,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    marginBottom: 8,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardTilePlaceholderText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
  },
  cardTileTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0f172a',
  },
  webFallback: {
    flex: 1,
    padding: 8,
    backgroundColor: '#ffffff',
  },
  webFallbackContent: {
    minWidth: '100%',
  },
  previewTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 4,
  },
  previewCode: {
    fontSize: 11,
    color: '#475569',
    fontFamily: 'Courier',
  },
});
